spring.application.name=${SPRING_APPLICATION_NAME}

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework=DEBUG
logging.level.com.safetrip=DEBUG
spring.servlet.multipart.max-file-size=20MB

# JWT config
jwt.secret=${JWT_SECRET_KEY}
jwt.expirationMs=${SECURITY_JWT_EXPIRATION_TIME}

# Mail config
mailtrap.token=${MAILTRAP_TOKEN}
mailtrap.inbox=3905346

# Cargar variables desde .env
spring.config.import=optional:file:.env[.properties]

# Variables globales
spring.jackson.time-zone=America/Bogota
spring.jpa.properties.hibernate.jdbc.time_zone=America/Bogota
whatsapp.url=${WSP_NOTIFICATION_URL}
whatsapp.api-key=${WSP_API_KEY}

# MinIO Config
minio.url=${MINIO_URL}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket=${MINIO_BUCKET}

# Encryption
encryption.key=${ENCRYPTION_KEY}

# Zurich Config
zurich.config.id=${ZURICH_CONFIG_ID}
zurich.confirmation-url=${ZURICH_CONFIRMATION_URL}
zurich.confirmation-url.custom-ap=${ZURICH_CONFIRMATION_URL_CUSTOM_AP}
zurich.confirmation-url.custom-sh=${ZURICH_CONFIRMATION_URL_CUSTOM_SH}
zurich.confirmation-url.custom-rc=${ZURICH_CONFIRMATION_URL_CUSTOM_RC}
zurich.response-url=${ZURICH_RESPONSE_URL}

# Cors
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
cors.allowed-methods=${CORS_ALLOWED_METHODS}
cors.allowed-headers=${CORS_ALLOWED_HEADERS}
cors.exposed-headers=${CORS_EXPOSED_HEADERS}
cors.max-age=${CORS_MAX_AGE}

# PDF Templates
pdf.template.policy01Ap=classpath:templates/template01Ap.pdf
pdf.template.policy02Ap=classpath:templates/template02Ap.pdf
pdf.template.policy01Sh=classpath:templates/template01Sh.pdf
pdf.template.policy02Sh=classpath:templates/template02Sh.pdf
pdf.template.policy02File=classpath:templates/template02File.pdf
pdf.template.policy01ApPax=classpath:templates/template01ApPax.pdf
pdf.template.policy02ApPax=classpath:templates/template02ApPax.pdf

# Resend config
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.ssl.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE}
spring.mail.properties.mail.smtp.connectiontimeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT}
spring.mail.properties.mail.smtp.timeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT}
spring.mail.properties.mail.smtp.writetimeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT}

app.mail.from=${APP_MAIL_FROM}
mail.to.policy=${MAIL_TO_POLICY}

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.syntaxHighlight.activated=true
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.packages-to-scan=com.safetrip.backend
springdoc.paths-to-match=/api/**
springdoc.show-actuator=false
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json